FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
EXPOSE 9002

WORKDIR /app/order
# RUN go test -v ./api/controllers ./api/services ./api/repositories
RUN go build -v -o main .


CMD ["/app/main"]
